# Generated by Django 4.2.5 on 2024-03-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regusername', models.CharField(max_length=100)),
                ('regusn', models.CharField(max_length=10)),
                ('regbranch', models.CharField(max_length=5)),
                ('regphone', models.DecimalField(decimal_places=10, max_digits=10)),
                ('regpassword', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
