# Generated by Django 4.2.5 on 2024-03-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='regusn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
