# Generated by Django 4.2.5 on 2024-03-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_register_regusn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='regphone',
            field=models.CharField(max_length=10),
        ),
    ]
