# Generated by Django 4.2.5 on 2024-03-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_register_regphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='regbranch',
            new_name='BRANCH',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='regpassword',
            new_name='PASSWORD',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='regphone',
            new_name='PHONE',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='date',
            new_name='REGISTRATION_DATE',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='regusername',
            new_name='USER_NAME',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='regusn',
            new_name='USN',
        ),
    ]
