# Generated by Django 4.2.5 on 2024-03-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rename_regbranch_register_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='USER_NAME',
            new_name='STUDENT_NAME',
        ),
    ]
