# Generated by Django 4.2.5 on 2024-03-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_register_id_alter_register_usn'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLogout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=10)),
                ('PASSWORD', models.CharField(max_length=15)),
                ('STATUS', models.CharField(max_length=6)),
            ],
        ),
    ]
