# Generated by Django 4.2.5 on 2024-03-01 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_loginlogout'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlogout',
            name='LOGIN_LOGOUT_TIME',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='loginlogout',
            name='USN',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attendance.register'),
        ),
    ]
