# Generated by Django 4.2.5 on 2024-03-02 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_loginlogout_login_logout_time_alter_loginlogout_usn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogout',
            name='LOGIN_LOGOUT_TIME',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 0, 0)),
        ),
    ]
