# Generated by Django 4.2.5 on 2024-03-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_loginlogout_login_logout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUDENT_NAME', models.CharField(max_length=100)),
                ('USN', models.CharField(default=None, max_length=10)),
                ('BRANCH', models.CharField(max_length=5)),
                ('LAST_LOGIN', models.DateTimeField()),
                ('ATTENDANCE', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='loginlogout',
            name='LOGIN_LOGOUT_TIME',
            field=models.DateTimeField(default='2024-03-02 11:56:02'),
        ),
    ]
